"""remove owner column from assets

Revision ID: 154f0a6d0ed2
Revises: e5a28f1427ba
Create Date: 2026-05-04 21:53:10.403922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154f0a6d0ed2'
down_revision: Union[str, Sequence[str], None] = 'e5a28f1427ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
