"""init commit

Revision ID: 70f6f7bb9017
Revises: 
Create Date: 2026-04-29 22:39:48.196748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70f6f7bb9017'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('asset_project_id', sa.UUID(), nullable=False, foreign_key='projects.project_id'),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=False),
    sa.Column('asset_config', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('owner', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('asset_name')
    )
    op.create_index('asset_project_id_index', 'assets', ['asset_project_id'], unique=False)
    op.create_index('asset_type_index', 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=True)
    op.create_table('data_chunks',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('chunk_asset_id', sa.UUID(), nullable=False, foreign_key='assets.asset_id'),
    sa.Column('chunk_project_id', sa.UUID(), nullable=False, foreign_key='projects.project_id'),
    sa.Column('chunk_content', sa.String(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('chunk_asset_id_index', 'data_chunks', ['chunk_asset_id'], unique=False)
    op.create_index('chunk_project_id_index', 'data_chunks', ['chunk_project_id'], unique=False)
    op.create_index(op.f('ix_data_chunks_chunk_id'), 'data_chunks', ['chunk_id'], unique=True)
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('owner', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=True)
    op.create_index(op.f('ix_projects_project_name'), 'projects', ['project_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_project_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_data_chunks_chunk_id'), table_name='data_chunks')
    op.drop_index('chunk_project_id_index', table_name='data_chunks')
    op.drop_index('chunk_asset_id_index', table_name='data_chunks')
    op.drop_table('data_chunks')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_index('asset_type_index', table_name='assets')
    op.drop_index('asset_project_id_index', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
