"""create celery task execution table

Revision ID: 95f2550d87c8
Revises: fa94aad21a42
Create Date: 2026-07-19 18:26:40.982944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f2550d87c8'
down_revision: Union[str, Sequence[str], None] = 'fa94aad21a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_name_args_hash'), table_name='celery_task_executions')
    op.create_index('ix_task_name_args_celery_id_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_args_celery_id_hash', table_name='celery_task_executions')
    op.create_index(op.f('ix_task_name_args_hash'), 'celery_task_executions', ['task_name', 'task_args_hash'], unique=True)
    # ### end Alembic commands ###
