"""create celery task execution table

Revision ID: ba94eb50886c
Revises: 154f0a6d0ed2
Create Date: 2026-07-19 16:55:48.435566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba94eb50886c'
down_revision: Union[str, Sequence[str], None] = '154f0a6d0ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_1536_22a3fcd9-90ec-4c6f-aa60-8aa141e44d4a', if_exists=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_1536_22a3fcd9-90ec-4c6f-aa60-8aa141e44d4a',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['data_chunks.chunk_id'], name=op.f('collection_1536_22a3fcd9-90ec-4c6f-aa60-8aa141e44_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_1536_22a3fcd9-90ec-4c6f-aa60-8aa141e44d4a_pkey'))
    )
    # ### end Alembic commands ###
