"""init commit

Revision ID: e5a28f1427ba
Revises: 70f6f7bb9017
Create Date: 2026-04-29 22:44:05.974600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a28f1427ba'
down_revision: Union[str, Sequence[str], None] = '70f6f7bb9017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'assets', 'projects', ['asset_project_id'], ['project_id'])
    op.create_foreign_key(None, 'data_chunks', 'projects', ['chunk_project_id'], ['project_id'])
    op.create_foreign_key(None, 'data_chunks', 'assets', ['chunk_asset_id'], ['asset_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_chunks', type_='foreignkey')
    op.drop_constraint(None, 'data_chunks', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    # ### end Alembic commands ###
