services:
  mongodb:
    image: mongo:latest
    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongodbdata:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - backend
    restart: always

networks:
  backend:
volumes:
  mongodbdata: